version: '3'
services:
  data:
    build:
      context: .
      target: data
    volumes:
      - ./data:/app/data
  
  solr:
    build:
      context: .
      target: solr
    ports:
      - 8983:8983
    volumes:
      - ./data/processed:/stories
      - ./solr:/data
  
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      SOLR_URL: http://solr:8983/solr
